site_name: 安全运营之路

theme:
        name: 'material'

nav:
        - 'index.md'
        - '对安全运营的理解': '0x0理解/对安全运营的理解.md'
        
        - 'About':
                - 'About': 'about/about.md'
                - 'Release Notes': 'about/releaseNotes.md'        