site_name: 安全运营之路

theme:
        name: 'material'

nav:
        - 'index.md'
        - 'About':
                - 'About': 'about/about.md'
                - 'Release Notes': 'about/releaseNotes.md'
        - 'TestCase': 'test.md'
